on:
  push:
    branches: [main]
    paths: ['README.md','build-from-source.md','setup-from-scratch.md','procedure-explanation.md']

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/0.8.0/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup --hide-footer README.md
          ./gh-md-toc --insert --no-backup --hide-footer build-from-source.md
          ./gh-md-toc --insert --no-backup --hide-footer setup-from-scratch.md
          ./gh-md-toc --insert --no-backup --hide-footer procedure-explanation.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update README TOC
